name: flake checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'
      - 'ci*'

permissions:
  contents: read

jobs:
  fmt:
    uses: ./.github/workflows/check-agnostic.yml
    with:
      check: fmt
  deny:
    uses: ./.github/workflows/check-agnostic.yml
    with:
      check: deny
  build-linux:
    uses: ./.github/workflows/check-linux.yml
    with:
      check: crane-package
    needs: [fmt, deny]
  clippy-linux:
    uses: ./.github/workflows/check-linux.yml
    with:
      check: clippy
    needs: build-linux
  build-macos:
    uses: ./.github/workflows/check-macos.yml
    with:
      check: crane-package
    needs: [fmt, deny]
  clippy-macos:
    uses: ./.github/workflows/check-macos.yml
    with:
      check: clippy
    needs: build-macos
