name: flake checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'
      - 'ci*'

permissions:
  contents: read

jobs:
  fmt:
    uses: ./.github/workflows/check.yml
    with:
      check: fmt
  deny:
    uses: ./.github/workflows/check.yml
    with:
      check: deny
  build:
    uses: ./.github/workflows/check.yml
    with:
      check: crane-package
    needs: [fmt, deny]
  clippy:
    uses: ./.github/workflows/check.yml
    with:
      check: clippy
    needs: build
    
