name: flake checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'
      - 'ci*'

permissions:
  contents: read

jobs:
  fmt:
    uses: ./.github/workflows/check-agnostic.yml
    with:
      check: fmt
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  deny:
    uses: ./.github/workflows/check-agnostic.yml
    with:
      check: deny
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  clippy:
    uses: ./.github/workflows/check-agnostic.yml
    with:
      check: clippy
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
    needs: [fmt, deny]
  build-linux:
    uses: ./.github/workflows/check-linux.yml
    with:
      check: crane-package
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
    needs: [fmt, deny]
  build-macos:
    uses: ./.github/workflows/check-macos.yml
    with:
      check: crane-package
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
    needs: [fmt, deny]
